import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navebar from "./components/Navebar";
import Hero from "./components/Hero";
import Text from "./components/Text";
import Cards from "./components/Cards";
import Slides from "./components/Slides";
import Footer from "./components/Footer";
import Courses from "./Courses/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen`}
      >
        <Navebar />
        <Hero />
        <Text />
        <Cards />
        <Slides />
        <Courses/>
      
        {children}
        <Footer />
      </body>
    </html>
  );
}
